image:
  repository: elizadevopsacr.azurecr.io/web
<<<<<<< HEAD
  tag: "31" # CI/Jenkins будут менять
=======
  tag: "v4" # CI/Jenkins будут менять
>>>>>>> d857add (Point web to image tag v4)
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
env:
  API_URL: "http://api-svc:3001"
resources: {}
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
