# ========== API CONFIG ==========
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
data:
  NODE_ENV: "production"

  
  DB_HOST: "mysql-service.default.svc.cluster.local"
  DB_NAME: "appdb"
  DB_PORT: "3306"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  NODE_ENV: "production"


  API_HOST: "http://api-service:3000"
